<script setup lang="ts">
import { DateTime } from 'luxon'
import { computed } from 'vue'

interface Props {
  appName?: string
  lastUpdatedIsoDate?: string
}

const props = withDefaults(defineProps<Props>(), {
  appName: 'QR Reader',
  lastUpdatedIsoDate: '2023-04-04',
})

const updatedDate = computed(() => {
  const dateTime = DateTime.fromISO(props.lastUpdatedIsoDate)

  return dateTime.toLocaleString(DateTime.DATE_MED)
})
</script>

<template>
  <h2>Privacy Policy</h2>
  <small>last updated: {{ updatedDate }}</small>
  <p>
    This Privacy Policy outlines our policies and procedures for collecting,
    using, and disclosing your information when you use our service. It also
    explains your privacy rights and how the law protects you. By using our
    service, you agree to our collection and use of your information in
    accordance with this Privacy Policy.
  </p>
  <h3>Interpretation and Definitions</h3>
  <h4>Interpretation</h4>
  <p>
    The words of which the initial letter is capitalized have meanings defined
    under the following conditions. The following definitions shall have the
    same meaning regardless of whether they appear in singular or in plural.
  </p>
  <h4>Definitions</h4>
  <p>For the purposes of this Privacy Policy:</p>
  <ul>
    <li>
      <p>
        <strong>Account</strong> means a unique account created for You to
        access our Service or parts of our Service.
      </p>
    </li>
    <li>
      <p>
        <strong>Affiliate</strong> means an entity that controls, is controlled
        by or is under common control with a party, where &quot;control&quot;
        means ownership of 50% or more of the shares, equity interest or other
        securities entitled to vote for election of directors or other managing
        authority.
      </p>
    </li>
    <li>
      <p>
        <strong>Company</strong> (referred to as either &quot;the Company&quot;,
        &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement)
        refers to QR Reader.
      </p>
    </li>
    <li>
      <p>
        <strong>Cookies</strong> are small files that are placed on Your
        computer, mobile device or any other device by a website, containing the
        details of Your browsing history on that website among its many uses.
      </p>
    </li>
    <li>
      <p><strong>Country</strong> refers to: United Kingdom</p>
    </li>
    <li>
      <p>
        <strong>Device</strong> means any device that can access the Service
        such as a computer, a cellphone or a digital tablet.
      </p>
    </li>
    <li>
      <p>
        <strong>Personal Data</strong> is any information that relates to an
        identified or identifiable individual.
      </p>
    </li>
    <li>
      <p><strong>Service</strong> refers to the Website.</p>
    </li>
    <li>
      <p>
        <strong>Service Provider</strong> means any natural or legal person who
        processes the data on behalf of the Company. It refers to third-party
        companies or individuals employed by the Company to facilitate the
        Service, to provide the Service on behalf of the Company, to perform
        services related to the Service or to assist the Company in analyzing
        how the Service is used.
      </p>
    </li>
    <li>
      <p>
        <strong>Usage Data</strong> refers to data collected automatically,
        either generated by the use of the Service or from the Service
        infrastructure itself (for example, the duration of a page visit).
      </p>
    </li>
    <li>
      <p>
        <strong>Website</strong> refers to QR Reader, accessible from
        <a
          href="http://qr-reader.net"
          rel="external nofollow noopener"
          target="_blank"
          >http://qr-reader.net</a
        >
      </p>
    </li>
    <li>
      <p>
        <strong>You</strong> means the individual accessing or using the
        Service, or the company, or other legal entity on behalf of which such
        individual is accessing or using the Service, as applicable.
      </p>
    </li>
  </ul>
  <h3>Google AdSense</h3>
  <p>
    We use Google AdSense to serve adverts to you. Google AdSense uses cookies
    to personalize ads and to analyze traffic. Information about your use of
    this site is shared with Google. By using this site, you agree to its use of
    cookies.
  </p>
  <h3>Changes to this Privacy Policy</h3>
  <p>
    We may update Our Privacy Policy from time to time. We will notify You of
    any changes by posting the new Privacy Policy on this page.
  </p>
  <p>
    We will let You know via email and/or a prominent notice on Our Service,
    prior to the change becoming effective and update the &quot;Last
    updated&quot; date at the top of this Privacy Policy.
  </p>
  <p>
    You are advised to review this Privacy Policy periodically for any changes.
    Changes to this Privacy Policy are effective when they are posted on this
    page.
  </p>
  <h3>Contact Us</h3>
  <p>
    If you have any questions about this Privacy Policy, You can contact us:
  </p>
  <ul>
    <li>By email: privacy@thirdwheelstudios.com</li>
  </ul>
</template>
